# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iMHtd4MVVeuWLsg2MLrEa_05W5FdKxGp
"""

import streamlit as st
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

# Fetch live data
url = "https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv"
df = pd.read_csv(url)

# Data preparation (same as your notebook)
for col in df.select_dtypes('object').columns:
    if col not in ['customerID', 'Churn']:
        df[col] = pd.factorize(df[col])[0]
df['Churn'] = df['Churn'].map({'No': 0, 'Yes': 1})

X = df.drop(['customerID','Churn'], axis=1)
y = df['Churn']

# Train model (for demo purposes, retrain each time — for production, save/load model)
model = RandomForestClassifier(n_estimators=100)
model.fit(X, y)

st.title('Telco Customer Churn Dashboard')
st.write('## Key Data')
st.dataframe(df.head(20))

st.write('## Predict Churn for Custom Input')
user_data = {}
for col in X.columns:
    user_data[col] = st.number_input(col, value=int(df[col].median()))
input_df = pd.DataFrame([user_data])

if st.button('Predict'):
    pred = model.predict(input_df)
    st.write(f"**Churn Prediction:** {'Yes' if pred[0]==1 else 'No'}")

st.write('## Feature Importance')
importances = pd.Series(model.feature_importances_, index=X.columns)
st.bar_chart(importances.sort_values(ascending=False)[:10])